// Extensión de queries.js - Nuevas categorías v1.0.2
// Este archivo añade nuevas categorías de búsqueda para mayor variedad

const queriesExtension = {
    gaming: [
        "Best gaming headsets [year]",
        "Top PC games of [year]",
        "Upcoming video games [year]",
        "Best gaming monitors [year]",
        "Gaming keyboard reviews [year]",
        "Top esports teams [year]",
        "Best indie games [year]",
        "Gaming mouse comparison [year]",
        "Best RPG games [year]",
        "Top multiplayer games [year]",
        "Gaming chair reviews [year]",
        "Best VR games [year]",
        "Steam sale dates [year]",
        "Best free-to-play games [year]",
        "Gaming laptop recommendations [year]",
        "Best battle royale games [year]",
        "Top survival games [year]",
        "Best MMORPGs [year]",
        "Gaming desk setup ideas",
        "Best racing games [year]",
        "Top fighting games [year]",
        "Best strategy games [year]",
        "Gaming webcam reviews [year]",
        "Best horror games [year]",
        "Top simulation games [year]",
        "Best sports games [year]",
        "Gaming microphone recommendations",
        "Best puzzle games [year]",
        "Top adventure games [year]",
        "Best roguelike games [year]",
        "Gaming GPU comparison [year]",
        "Best sandbox games [year]",
        "Top stealth games [year]",
        "Best platformer games [year]",
        "Gaming controller reviews [year]",
        "Best metroidvania games [year]",
        "Top cooperative games [year]",
        "Best single-player games [year]",
        "Gaming streaming setup guide",
        "Best open world games [year]",
        "Top tower defense games [year]",
        "Best card games [year]",
        "Gaming SSD recommendations [year]",
        "Best turn-based games [year]",
        "Top action games [year]",
        "Best shooter games [year]",
        "Gaming RAM requirements [year]",
        "Best narrative games [year]",
        "Top casual games [year]",
        "Best early access games [year]",
        "PlayStation 5 games [year]",
        "Xbox Series X games [year]",
        "Nintendo Switch games [year]",
        "Game Pass best games [year]",
        "Best couch co-op games",
        "Gaming accessories guide [year]",
        "Retro gaming consoles",
        "Best gaming soundtracks",
        "Upcoming game releases [year]",
        "Gaming industry news [year]",
        "Best game trailers [year]",
        "Top Twitch streamers [year]",
        "Gaming community events [year]",
        "Best game mods [year]",
        "Gaming setup inspiration",
        "Esports tournaments [year]",
        "Game of the Year predictions [year]",
        "Best remakes and remasters [year]",
        "Gaming deals and discounts",
        "How to improve gaming performance",
        "Best games for beginners",
        "Gaming trends [year]",
        "Most anticipated games [year]",
        "Best game developers [year]",
        "Gaming gift ideas [year]",
        "Best game soundtracks [year]",
        "Gaming room decoration ideas",
        "Best game DLCs [year]",
        "Gaming subscription services comparison",
        "Best games on sale [year]"
    ],
    sports: [
        "Champions League results [year]",
        "NBA standings [year]",
        "Premier League table [year]",
        "NFL playoff schedule [year]",
        "Formula 1 calendar [year]",
        "Tennis Grand Slam winners [year]",
        "World Cup qualifiers [year]",
        "Olympic Games highlights [year]",
        "Boxing matches schedule [year]",
        "MMA UFC fight cards [year]",
        "Golf tournament results [year]",
        "Cricket World Cup [year]",
        "Baseball MLB standings [year]",
        "Hockey NHL playoffs [year]",
        "Athletics world records [year]",
        "Swimming championships [year]",
        "Cycling Tour de France [year]",
        "Rugby World Cup [year]",
        "Basketball Euroleague [year]",
        "Handball championships [year]",
        "Volleyball world league [year]",
        "Table tennis competitions [year]",
        "Badminton tournaments [year]",
        "Gymnastics results [year]",
        "Winter sports events [year]",
        "Skiing world cup [year]",
        "Snowboarding championships [year]",
        "Figure skating results [year]",
        "Speed skating records [year]",
        "Motorsport news [year]",
        "Rally championship [year]",
        "MotoGP calendar [year]",
        "IndyCar series [year]",
        "NASCAR results [year]",
        "Football transfer news [year]",
        "Player salary rankings [year]",
        "Sports betting tips",
        "Fantasy football advice [year]",
        "Sports injury updates [year]",
        "Coaching changes [year]",
        "Stadium capacity rankings",
        "Sports equipment reviews",
        "Fitness training tips",
        "Running marathon training",
        "CrossFit workout routines",
        "Yoga for athletes",
        "Sports nutrition guide",
        "Strength training programs",
        "Cardio exercises at home",
        "Sports recovery techniques",
        "Best sports apps [year]",
        "Live sports streaming",
        "Sports highlights [year]",
        "Best sports moments [year]",
        "Sports documentaries [year]",
        "Athlete of the year [year]",
        "Sports controversies [year]",
        "Record-breaking performances [year]",
        "Sports awards [year]",
        "Hall of Fame inductees [year]"
    ],
    cooking: [
        "Easy dinner recipes",
        "Healthy meal prep ideas",
        "Quick breakfast recipes",
        "Vegetarian recipes for beginners",
        "Vegan dinner ideas",
        "Low carb recipes [year]",
        "Keto diet meal plans",
        "Mediterranean diet recipes",
        "Asian cuisine recipes",
        "Italian pasta recipes",
        "Mexican food recipes",
        "Indian curry recipes",
        "French cooking techniques",
        "Japanese sushi recipes",
        "Thai food recipes",
        "Chinese stir fry recipes",
        "Korean BBQ recipes",
        "Greek salad recipes",
        "Spanish tapas recipes",
        "Middle Eastern cuisine",
        "Best air fryer recipes",
        "Instant Pot recipes",
        "Slow cooker meals",
        "One pot dinner ideas",
        "Sheet pan dinners",
        "Meal planning tips",
        "Budget cooking recipes",
        "Student meal ideas",
        "Family dinner recipes",
        "Date night cooking ideas",
        "Dessert recipes easy",
        "Cake baking tips",
        "Cookie recipes homemade",
        "Bread baking recipes",
        "Pizza dough recipe",
        "Smoothie recipes healthy",
        "Juice cleanse recipes",
        "Protein shake recipes",
        "Healthy snack ideas",
        "Appetizer recipes",
        "Soup recipes for winter",
        "Salad dressing recipes",
        "BBQ recipes summer",
        "Grilling tips and tricks",
        "Smoking meat guide",
        "Sous vide cooking",
        "Kitchen gadget reviews [year]",
        "Best cookware [year]",
        "Knife set recommendations",
        "Food processor recipes",
        "Stand mixer recipes",
        "Blender smoothies",
        "Cooking for one tips",
        "Batch cooking ideas",
        "Freezer meal prep",
        "Leftover recipe ideas",
        "Zero waste cooking",
        "Seasonal cooking recipes",
        "Holiday dinner recipes",
        "Christmas cookie recipes",
        "Thanksgiving menu ideas",
        "Easter brunch recipes",
        "Food trends [year]",
        "Restaurant recipes at home",
        "Chef techniques at home",
        "Cooking channel recipes",
        "Best cooking apps [year]",
        "Online cooking classes",
        "Culinary school tips",
        "Food photography tips"
    ],
    health: [
        "How to sleep better",
        "Stress relief techniques",
        "Mental health tips [year]",
        "Anxiety management strategies",
        "Depression support resources",
        "Meditation for beginners",
        "Mindfulness exercises",
        "Breathing techniques for calm",
        "Work-life balance tips",
        "Burnout prevention strategies",
        "Home workout routines",
        "Gym exercises for beginners",
        "Weight loss tips [year]",
        "Muscle building guide",
        "Flexibility exercises",
        "Core strengthening workout",
        "Back pain relief exercises",
        "Neck stretch exercises",
        "Posture improvement tips",
        "Desk ergonomics guide",
        "Healthy eating habits",
        "Nutrition facts guide",
        "Vitamin supplements guide",
        "Immune system boosters",
        "Anti-inflammatory foods",
        "Heart healthy diet",
        "Diabetes prevention tips",
        "Blood pressure management",
        "Cholesterol lowering foods",
        "Gut health improvement",
        "Probiotic foods list",
        "Hydration importance tips",
        "Detox water recipes",
        "Fasting benefits guide",
        "Intermittent fasting tips",
        "Plant-based diet benefits",
        "Superfoods list [year]",
        "Organic food benefits",
        "Food allergy guide",
        "Gluten-free recipes",
        "Skin care routine tips",
        "Hair care guide",
        "Dental health tips",
        "Eye health exercises",
        "Hearing protection tips",
        "First aid basics",
        "Emergency preparedness guide",
        "Health screenings [year]",
        "Vaccination schedule [year]",
        "Telemedicine services [year]",
        "Health insurance tips",
        "Doctor appointment checklist",
        "Medical test preparation",
        "Hospital care tips",
        "Home remedies guide",
        "Natural healing methods",
        "Herbal supplements guide",
        "Essential oils benefits",
        "Aromatherapy for relaxation",
        "Chiropractic benefits"
    ],
    news: [
        "Latest world news today",
        "Breaking news updates",
        "Politics news [year]",
        "Economy news today",
        "Stock market updates",
        "Cryptocurrency news [year]",
        "Technology news today",
        "Science discoveries [year]",
        "Space exploration news [year]",
        "Climate change news [year]",
        "Environment news today",
        "Health news updates",
        "COVID updates [year]",
        "Pandemic news today",
        "International relations news",
        "Diplomacy news [year]",
        "Military news updates",
        "Defense industry news",
        "Cybersecurity news [year]",
        "Data breach news today",
        "Privacy news [year]",
        "Social media news",
        "Tech company news [year]",
        "Startup news today",
        "AI news [year]",
        "Robotics news updates",
        "Electric vehicle news [year]",
        "Renewable energy news",
        "Solar power news [year]",
        "Wind energy updates",
        "Nuclear energy news",
        "Oil and gas industry news",
        "Mining industry news",
        "Agriculture news today",
        "Food industry news",
        "Retail industry news [year]",
        "E-commerce news today",
        "Real estate news [year]",
        "Housing market updates",
        "Banking news today",
        "Financial services news",
        "Insurance industry news",
        "Travel industry news [year]",
        "Airline news today",
        "Hospitality industry news",
        "Entertainment news today",
        "Celebrity news [year]",
        "Music industry news",
        "Film industry news [year]",
        "TV show news today",
        "Streaming service news",
        "Publishing industry news",
        "Book news [year]",
        "Art world news today",
        "Fashion industry news [year]",
        "Luxury goods news",
        "Automotive industry news",
        "Transportation news [year]",
        "Shipping industry news",
        "Logistics news today"
    ],
    spanish: [
        "Recetas de cocina fáciles",
        "Noticias de España hoy",
        "Tiempo en Madrid",
        "Resultados de fútbol La Liga",
        "Películas españolas [year]",
        "Series de Netflix España",
        "Música latina nueva [year]",
        "Libros recomendados [year]",
        "Destinos turísticos España",
        "Ofertas de viaje [year]",
        "Cursos online gratis",
        "Aprender inglés online",
        "Trabajo remoto España",
        "Emprendimiento digital",
        "Inversiones para principiantes",
        "Criptomonedas guía básica",
        "Ahorro doméstico tips",
        "Préstamos personales",
        "Hipotecas mejores ofertas",
        "Seguros de coche comparativa",
        "Móviles recomendados [year]",
        "Ordenadores portátiles [year]",
        "Tablets mejores opciones",
        "Smart TV comparativa",
        "Auriculares inalámbricos",
        "Consejos de salud",
        "Ejercicios en casa",
        "Dietas saludables [year]",
        "Meditación para principiantes",
        "Yoga en casa rutina",
        "Recetas vegetarianas",
        "Postres caseros fáciles",
        "Cócteles para fiestas",
        "Vinos españoles mejores",
        "Cerveza artesanal España",
        "Restaurantes recomendados",
        "Comida a domicilio",
        "Supermercados online",
        "Compras por internet",
        "Amazon ofertas del día",
        "Decoración de interiores",
        "Jardinería consejos",
        "Mascotas cuidados básicos",
        "Perros razas populares",
        "Gatos cuidados especiales",
        "Coches eléctricos [year]",
        "Motos recomendadas [year]",
        "Bicicletas eléctricas",
        "Patinetes eléctricos",
        "Transporte público Madrid",
        "Trenes AVE horarios",
        "Vuelos baratos Europa",
        "Hoteles económicos",
        "Airbnb mejores destinos",
        "Camping España mejores",
        "Playas de España top",
        "Montañas España senderismo",
        "Pueblos bonitos España",
        "Ciudades para visitar",
        "Museos gratuitos España"
    ]
};

export { queriesExtension };
